version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3333:3333"
    command: sh -c "npm start"
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4444:4444"
    command: sh -c "npm start"
